# H2 Connection
spring:
  datasource:
    -url: jdbc:h2:mem:testdb
    -username: sa
    -password:
#H2 Client
  h2:
    console:
      -enable: true
      -path: /h2-console
# Show SQL 
  jpa:
    -show-sql: true
    profiles:
      hibernate:
        -format_sql: true
